# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: library
services:
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
  maildev:
    image: maildev/maildev:latest
    ports:
      - '1080:1080' # Web UI
      - '1025:1025' # SMTP server
    environment:
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
